# Generated by Django 5.0.2 on 2024-04-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=0.00045810428119273693, on_delete=django.db.models.deletion.CASCADE, to='emp_app.role'),
            preserve_default=False,
        ),
    ]
